### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by tarsius** [wbolster/emacs-gsettings#3]
The Emacsmirror uses `elx.el` to extract metadata, such as license information, from packages. Currently it does not understand:

```
;; Copyright 2019 wouter bolsterlee. Licensed under the 3-Clause BSD License.
```

I could add yet another special case to https://github.com/emacscollective/elx/blob/c554db7e7f2c0c8a503def7739b8205193ba821f/elx.el#L362 but I would rather not do that. Please consider adding a LICENSE file (that would also result in Github being able to detect the license) or adding the license text to the library header.

Same for `gvariant`.

**Comment by wbolster** [comment]
hey @tarsius, done in 1e38ebc9eca0ac6c42916f7e1bada3d86a5bff59

is the current format fine? if so i'll do the same for `gvariant.el`

**Comment by wbolster** [comment]
did the same for `gvariant.el`: https://github.com/wbolster/emacs-gvariant/commit/df7c6de199284e0e0c3f3569760229c89998b97d

**Comment by tarsius** [comment]
Github does not seem to recognize the license so elx won't either; it uses the same tool to do so. It appears you added to much additional information that throws of the matcher. You can create a new repository, select the license, and see what Github thinks that should look like.
